In [29]:
import matplotlib as plt
import numpy as np

from src import (
    eliminacion_gaussiana,
    descomposicion_LU,
    resolver_LU,
    matriz_aumentada,
    separar_m_aumentada,
)

def eliminacion_gaussiana(A: np.ndarray) -> np.ndarray:
    """Resuelve un sistema de ecuaciones lineales mediante el método de eliminación gaussiana.

    ## Parameters

    ``A``: matriz aumentada del sistema de ecuaciones lineales. Debe ser de tamaño n-by-(n+1), donde n es el número de incógnitas.

    ## Return

    ``solucion``: vector con la solución del sistema de ecuaciones lineales.

    """
    if not isinstance(A, np.ndarray):
        print("Convirtiendo A a numpy array.")
        A = np.array(A, dtype=float)
    assert A.shape[0] == A.shape[1] , "La matriz A debe ser de tamaño n-by-n."
    n = A.shape[0]
    numcambios = 0
    for i in range(0, n - 1):  # loop por columna

        # --- encontrar pivote
        p = None  # default, first element
        for pi in range(i, n):
            if A[pi, i] == 0:
                # must be nonzero
                continue

            if p is None:
                # first nonzero element
                p = pi
                continue

            if abs(A[pi, i]) < abs(A[p, i]):
                p = pi

        if p is None:
            # no pivot found.
            raise ValueError("No existe solución única.")

        if p != i:
            # swap rows
            print(f"Intercambiando filas {i} y {p}")
            _aux = A[i, :].copy()
            A[i, :] = A[p, :].copy()
            A[p, :] = _aux
            numcambios+=1

        # --- Eliminación: loop por fila
        for j in range(i + 1, n):
            m = A[j, i] / A[i, i]
            A[j, i:] = A[j, i:] - m * A[i, i:]

        print(f"\n{A}")

    
    return A,numcambios


# ####################################################################
def calc_determinante(A: list[list[float]]) -> float:
    """Función que calcula el determinante usando el método...
    [Descomposición LU, eliminación gaussiana, Gauss-Jordan, Gauss-Jacobi o Gauss-Seidel]

    ## Parameters
    ``A``: Matriz cuadrada de tamaño n x n

    ## Return
    ``detA``: Determinante de la matriz A

    """
    print("Matriz escalonada: \n\n")
    Det=1
    B,cambios=eliminacion_gaussiana(A)
    for fila in B:
        print(fila)

    for i in range(len(B)):
        for j in range(len(B)): 
            if i==j: 
                Det*=B[i,j]
                print(Det)
        print("\n")        
            
    # completar
    return  Det*(-1)**cambios

In [30]:
A1 = [
    [-4, 2, -4, -4, 1, 2, 5, 3, 5, 1],
    [1, 0, 4, 3, 0, -2, 3, 0, 1, 5],
    [5, 5, -4, 5, -4, 2, 2, 2, 4, 4],
    [-1, 3, 4, -1, -4, 0, 5, 0, 0, 5],
    [4, 1, 4, 2, 0, 0, 3, -1, 0, 2],
    [2, -2, 1, -1, -2, -3, 2, -2, 4, -1],
    [3, -2, -3, -2, -1, -3, 5, -1, 5, 0],
    [3, 4, -3, 3, -2, 2, -4, -4, 1, 5],
    [-4, 0, 3, 3, -3, -2, -2, 0, 5, -4],
    [-2, 4, 4, -2, -1, 1, 5, -1, 3, -3],
]
calc_determinante(A1)

Matriz escalonada: 


Convirtiendo A a numpy array.
Intercambiando filas 0 y 1

[[  1.   0.   4.   3.   0.  -2.   3.   0.   1.   5.]
 [  0.   2.  12.   8.   1.  -6.  17.   3.   9.  21.]
 [  0.   5. -24. -10.  -4.  12. -13.   2.  -1. -21.]
 [  0.   3.   8.   2.  -4.  -2.   8.   0.   1.  10.]
 [  0.   1. -12. -10.   0.   8.  -9.  -1.  -4. -18.]
 [  0.  -2.  -7.  -7.  -2.   1.  -4.  -2.   2. -11.]
 [  0.  -2. -15. -11.  -1.   3.  -4.  -1.   2. -15.]
 [  0.   4. -15.  -6.  -2.   8. -13.  -4.  -2. -10.]
 [  0.   0.  19.  15.  -3. -10.  10.   0.   9.  16.]
 [  0.   4.  12.   4.  -1.  -3.  11.  -1.   5.   7.]]
Intercambiando filas 1 y 4

[[  1.   0.   4.   3.   0.  -2.   3.   0.   1.   5.]
 [  0.   1. -12. -10.   0.   8.  -9.  -1.  -4. -18.]
 [  0.   0.  36.  40.  -4. -28.  32.   7.  19.  69.]
 [  0.   0.  44.  32.  -4. -26.  35.   3.  13.  64.]
 [  0.   0.  36.  28.   1. -22.  35.   5.  17.  57.]
 [  0.   0. -31. -27.  -2.  17. -22.  -4.  -6. -47.]
 [  0.   0. -39. -31.  -1.  19. -22.  -3.  

np.float64(9912775.999999994)

In [31]:
A2 = [
    [2, 2, 4, 5, -2, -3, 2, -2],
    [-1, -1, 3, 2, 1, 1, -4, 4],
    [2, 5, -3, -3, -2, 2, 5, 3],
    [-2, -4, 0, 1, -1, 5, -4, -1],
    [1, -2, -1, 5, 5, 2, 1, -2],
    [5, 4, 0, 3, 4, -1, -3, -2],
    [4, -4, 1, 2, 3, 3, -1, 3],
    [-2, 1, -3, 0, 5, 4, 4, -4],
]
calc_determinante(A2)

Matriz escalonada: 


Convirtiendo A a numpy array.
Intercambiando filas 0 y 1

[[ -1.  -1.   3.   2.   1.   1.  -4.   4.]
 [  0.   0.  10.   9.   0.  -1.  -6.   6.]
 [  0.   3.   3.   1.   0.   4.  -3.  11.]
 [  0.  -2.  -6.  -3.  -3.   3.   4.  -9.]
 [  0.  -3.   2.   7.   6.   3.  -3.   2.]
 [  0.  -1.  15.  13.   9.   4. -23.  18.]
 [  0.  -8.  13.  10.   7.   7. -17.  19.]
 [  0.   3.  -9.  -4.   3.   2.  12. -12.]]
Intercambiando filas 1 y 5

[[  -1.   -1.    3.    2.    1.    1.   -4.    4.]
 [   0.   -1.   15.   13.    9.    4.  -23.   18.]
 [   0.    0.   48.   40.   27.   16.  -72.   65.]
 [   0.    0.  -36.  -29.  -21.   -5.   50.  -45.]
 [   0.    0.  -43.  -32.  -21.   -9.   66.  -52.]
 [   0.    0.   10.    9.    0.   -1.   -6.    6.]
 [   0.    0. -107.  -94.  -65.  -25.  167. -125.]
 [   0.    0.   36.   35.   30.   14.  -57.   42.]]
Intercambiando filas 2 y 5

[[ -1.   -1.    3.    2.    1.    1.   -4.    4. ]
 [  0.   -1.   15.   13.    9.    4.  -23.   18. ]
 [  0.  

np.float64(2341545.999999993)